#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'Camera-pkg==0.0.0','console_scripts','oakd_stereo'
__requires__ = 'Camera-pkg==0.0.0'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('Camera-pkg==0.0.0', 'console_scripts', 'oakd_stereo')()
    )
